//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Retail.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        internal static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        internal static string lblNext {
            get {
                return ResourceManager.GetString("lblNext", resourceCulture);
            }
        }
        
        internal static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        internal static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        internal static string lblSignin {
            get {
                return ResourceManager.GetString("lblSignin", resourceCulture);
            }
        }
        
        internal static string lblSignUp {
            get {
                return ResourceManager.GetString("lblSignUp", resourceCulture);
            }
        }
        
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        internal static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        internal static string lbltitelForgotPassword {
            get {
                return ResourceManager.GetString("lbltitelForgotPassword", resourceCulture);
            }
        }
        
        internal static string lblMsgEmailErrorForgotPassword {
            get {
                return ResourceManager.GetString("lblMsgEmailErrorForgotPassword", resourceCulture);
            }
        }
        
        internal static string lblMsgEmailValidErrorForgotPassword {
            get {
                return ResourceManager.GetString("lblMsgEmailValidErrorForgotPassword", resourceCulture);
            }
        }
        
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        internal static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        internal static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        internal static string lblErrorName {
            get {
                return ResourceManager.GetString("lblErrorName", resourceCulture);
            }
        }
        
        internal static string lblErrorEmail {
            get {
                return ResourceManager.GetString("lblErrorEmail", resourceCulture);
            }
        }
        
        internal static string lblErrorValidEmail {
            get {
                return ResourceManager.GetString("lblErrorValidEmail", resourceCulture);
            }
        }
        
        internal static string lblErrorContactNumber {
            get {
                return ResourceManager.GetString("lblErrorContactNumber", resourceCulture);
            }
        }
        
        internal static string lblErrorTitle {
            get {
                return ResourceManager.GetString("lblErrorTitle", resourceCulture);
            }
        }
        
        internal static string lblOk {
            get {
                return ResourceManager.GetString("lblOk", resourceCulture);
            }
        }
        
        internal static string inquery {
            get {
                return ResourceManager.GetString("inquery", resourceCulture);
            }
        }
        
        internal static string servererror {
            get {
                return ResourceManager.GetString("servererror", resourceCulture);
            }
        }
    }
}
